version: '2'

volumes:
  nextcloud:
  db:

services:
  gateway:
    image: nginx
    restart: always
    volumes:
      - /opt/docker-projects/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/docker-projects/nextcloud/nginx/nextcloud.conf:/etc/nginx/sites-enabled/nextcloud.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - "app"
      - "db"
    ports:
      - 80:80
      - 443:443
  db:
    image: mariadb
    command: mysqld --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /opt/docker-projects/nextcloud/data:/opt/nextcloud/data
      - /opt/docker-projects/nextcloud/nextcloud/custom.config.php:/var/www/html/config/custom.config.php
    restart: always
